/**
 * Privacy Policy Page
 *
 * Route: /privacy
 */
"use client";

import { Shield, Lock, Eye, Server, Cookie, Bell } from "lucide-react";
import { GlassCard, FadeIn, StaggerContainer, StaggerItem } from "@/components/ui";

// ---------------------------------------------------------------------------
// Content
// ---------------------------------------------------------------------------

const SECTIONS = [
  {
    icon: Eye,
    title: "What We Collect",
    content:
      "NorthStar Compass is a static website with minimal data collection. We do not create user accounts or store personal information on any server. We use PostHog (a privacy-focused analytics tool) to collect anonymous usage events such as page views and feature interactions. PostHog receives your anonymized session data, browser type, and general region, but no names, emails, or personally identifiable information. All analytics events are tagged with an environment label (dev, stage, or prod) for debugging purposes only.",
  },
  {
    icon: Lock,
    title: "Your Data Stays Local",
    content:
      "Any personalization data you enter (priority date, employer name, salary, etc.) is stored exclusively in your browser's localStorage under the `compass_` prefix. This data never leaves your device. We cannot see it, and we do not want to. You can clear it at any time by resetting your browser storage or using the Setup page.",
  },
  {
    icon: Server,
    title: "Hosting & Infrastructure",
    content:
      "Compass is hosted on AWS using S3 (static file storage) and CloudFront (CDN). Standard AWS access logs (IP address, timestamp, resource requested) are generated by CloudFront as part of normal CDN operation. These logs are not used for user tracking and are retained only as needed for infrastructure security.",
  },
  {
    icon: Cookie,
    title: "Cookies & Tracking",
    content:
      "We use PostHog for anonymous, privacy-focused product analytics. PostHog may set a cookie to distinguish unique sessions, but this cookie contains no personal data. We do not use Google Analytics, Facebook Pixel, Hotjar, or any advertising trackers. PostHog data is used solely to understand which features are used and to improve the product. The only other external resource is Google Fonts (Geist) loaded via Next.js font optimization.",
  },
  {
    icon: Bell,
    title: "Third-Party Data Sources",
    content:
      "The immigration data displayed on Compass is sourced from publicly available U.S. government datasets (DOL, DOS, BLS, USCIS, DHS). This data is pre-processed and bundled as static JSON files. No API calls are made to government servers from your browser.",
  },
  {
    icon: Shield,
    title: "Security",
    content:
      "All traffic is served over HTTPS with TLS 1.2+. The site implements Content-Security-Policy headers, XSS protections, and input sanitization. Since there is no backend, server, or database, the attack surface is minimal. The full source code is open for security review.",
  },
];

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

export default function PrivacyPage() {
  return (
    <div className="space-y-12">
      <section aria-label="Privacy header">
        <FadeIn>
          <div className="flex items-center gap-3 mb-2">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-emerald-500 to-cyan-500">
              <Shield className="h-5 w-5 text-white" strokeWidth={2} />
            </div>
            <div>
              <p className="text-[10px] font-mono uppercase tracking-widest text-[var(--muted-foreground)]">
                Legal
              </p>
              <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
                Privacy Policy
              </h1>
            </div>
          </div>
          <p className="mt-4 max-w-2xl text-sm leading-relaxed text-[var(--muted-foreground)]">
            The short version: we don&apos;t collect your data. The long version
            is below, written in plain language because legalese helps no one.
          </p>
          <p className="mt-2 text-xs text-[var(--muted-foreground)]">
            Last updated: March 23, 2026
          </p>
        </FadeIn>
      </section>

      <StaggerContainer className="space-y-4">
        {SECTIONS.map((s) => (
          <StaggerItem key={s.title}>
            <GlassCard variant="default" padding="md">
              <div className="flex items-start gap-4">
                <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-emerald-500/10">
                  <s.icon
                    className="h-4.5 w-4.5 text-emerald-400"
                    strokeWidth={1.5}
                  />
                </div>
                <div>
                  <h2 className="mb-1 text-sm font-semibold">{s.title}</h2>
                  <p className="text-xs leading-relaxed text-[var(--muted-foreground)]">
                    {s.content}
                  </p>
                </div>
              </div>
            </GlassCard>
          </StaggerItem>
        ))}
      </StaggerContainer>
    </div>
  );
}
